# Generated by Django 4.2.21 on 2025-06-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='measurement_unit',
        ),
    ]
